options:
  env:
  - SUBPROJECT_ID=tanaka-corpus
  - SHORT_SHA=$SHORT_SHA
  - BUILD_ID=$BUILD_ID
  - PROJECT_ID=$PROJECT_ID
steps:
- name: 'gcr.io/my-web-apis/install-utf8-builder'
- name: 'gcr.io/cloud-builders/wget'
  entrypoint: bash
  args: ['-c', 'mkdir /upload']
- name: 'gcr.io/cloud-builders/wget'
  args: ['http://www.edrdg.org/examples/examples_date']
- name: 'gcr.io/cloud-builders/wget'
  args: ['ftp://ftp.monash.edu/pub/nihongo/examples.utf.gz']
- name: 'gcr.io/my-web-apis/gunzip-builder'
  args: ['-k', 'examples.utf.gz']
- name: 'gcr.io/my-web-apis/inspect-builder'
- name: 'gcr.io/my-web-apis/upload-gs-builder'

